datasets:
  formula_rec_eval:
    data_type: images
    build_info:
      images: ./asset/test_imgs
      annotation: ./asset/test_imgs
    vis_processor:
      eval:
        name: "formula_image_eval"
        image_size:
          - 192
          - 672
    text_processor:
      eval:
        name: "blip_caption"
